# DataSource Configuration
spring:
  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}

  # Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true